micronaut:
  application:
    name: micronaut
  server:
    context-path: /api
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256

datasources:
  default:
    url: 'jdbc:h2:mem:realword;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

jpa:
  default:
    packages-to-scan:
      - 'io.realworld.app.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:migrations