version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/micronaut-kotlin-realworld-example-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run tests
          command: gradle test