CREATE TABLE `user` (
    id VARBINARY(16) NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255),
    bio VARCHAR(255),
    image VARCHAR(255)
) DEFAULT CHARSET=utf8;